## Трогаем датасет

На примере [Popular Sneakers Classification](https://www.kaggle.com/datasets/nikolasgegenava/sneakers-classification?resource=download)

In [37]:
import sys

sys.path.append('..')

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [38]:
from utils.eda_utils import directory_to_dataframe

path_to_dataset = '../archive/sneakers-dataset/sneakers-dataset'
df = directory_to_dataframe(path_to_dataset)
df

                                 path           sneaker_class
0     reebok_classic_leather/0071.jpg  reebok_classic_leather
1     reebok_classic_leather/0065.jpg  reebok_classic_leather
2     reebok_classic_leather/0059.jpg  reebok_classic_leather
3     reebok_classic_leather/0058.jpg  reebok_classic_leather
4     reebok_classic_leather/0064.jpg  reebok_classic_leather
...                               ...                     ...
5948         nike_air_max_97/0083.jpg         nike_air_max_97
5949         nike_air_max_97/0097.jpg         nike_air_max_97
5950         nike_air_max_97/0040.jpg         nike_air_max_97
5951         nike_air_max_97/0054.jpg         nike_air_max_97
5952         nike_air_max_97/0068.jpg         nike_air_max_97

[5953 rows x 2 columns]

In [41]:
df.query('sneaker_class == "yeezy_slide"')

                      path sneaker_class
1796  yeezy_slide/0071.jpg   yeezy_slide
1797  yeezy_slide/0065.jpg   yeezy_slide
1798  yeezy_slide/0059.jpg   yeezy_slide
1799  yeezy_slide/0105.jpg   yeezy_slide
1800  yeezy_slide/0111.jpg   yeezy_slide
...                    ...           ...
1936  yeezy_slide/0083.jpg   yeezy_slide
1937  yeezy_slide/0097.jpg   yeezy_slide
1938  yeezy_slide/0040.jpg   yeezy_slide
1939  yeezy_slide/0054.jpg   yeezy_slide
1940  yeezy_slide/0068.jpg   yeezy_slide

[145 rows x 2 columns]

In [46]:
from utils.eda_utils import sneaker_class_to_brand

class_to_brand = sneaker_class_to_brand(df["sneaker_class"].unique())

df['brand'] = df['sneaker_class'].map(class_to_brand)
df

                                 path           sneaker_class   brand
0     reebok_classic_leather/0071.jpg  reebok_classic_leather  reebok
1     reebok_classic_leather/0065.jpg  reebok_classic_leather  reebok
2     reebok_classic_leather/0059.jpg  reebok_classic_leather  reebok
3     reebok_classic_leather/0058.jpg  reebok_classic_leather  reebok
4     reebok_classic_leather/0064.jpg  reebok_classic_leather  reebok
...                               ...                     ...     ...
5948         nike_air_max_97/0083.jpg         nike_air_max_97    nike
5949         nike_air_max_97/0097.jpg         nike_air_max_97    nike
5950         nike_air_max_97/0040.jpg         nike_air_max_97    nike
5951         nike_air_max_97/0054.jpg         nike_air_max_97    nike
5952         nike_air_max_97/0068.jpg         nike_air_max_97    nike

[5953 rows x 3 columns]

In [49]:
df.groupby('brand').path.count().sort_values(ascending=False)

brand
nike           2295
adidas          950
new_balance     653
converse        544
vans            478
yeezy           401
reebok          246
puma            148
salomon         147
asics            91
Name: path, dtype: int64